### ISSUE TITLE
Java 16 incompatibility (InaccessibleObjectException)

### ISSUE THREAD

**Issue by AuroraLS3** [egg82/MVNLoader#1]
the addURL method has become inaccessible in Java 16.

```
java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @7ab0d6cd
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
        at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
        at net.playeranalytics.plugin.ninja.egg82.mvn.classloaders.TransparentInjectableClassLoader.<clinit>(TransparentInjectableClassLoader.java:28) ~[?:?]
        ... 8 more
```

~~I have very little experience with this, but I searched for some solutions and it seems reflection using `Method#setAccessible` might need to be performed within a `PrivilegedAction`~~ Tested this, did not work

(from https://stackoverflow.com/a/41265267, it has a lot more in-depth information)

Related tickets from my issue tracker if they're any help, gist is that dependencies are attempted to be injected during plugin loading (Not much more than the exception above).
- https://github.com/plan-player-analytics/Plan/issues/1886
- https://github.com/plan-player-analytics/Plan/issues/1839

**Comment by AuroraLS3** [comment]
These are the methods related to the issue `java.net.URLClassLoader.addURL(java.net.URL)`, `java.net.URLClassLoader.findClass(java.lang.String)`, `java.net.URLClassLoader.getPermissions(java.security.CodeSource)`
